plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "F:\\Anti-Gravity\\Marketing Agency\\Bell Acqua Lake\\web"
publishOrigin = "default"
base = "F:\\Anti-Gravity\\Marketing Agency\\Bell Acqua Lake\\web"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]